Repository sveltejs/svelte.dev, pull requests merged in 2025-09, with the labels that each got.

#1513 fix: remove trailing `=` signs from hash urls
  apps/svelte.dev/src/routes/(authed)/playground/[id]/gzip.js
Labels: playground (functionality)

#1519 fix: scrollbar background on search results
  packages/site-kit/src/lib/search/SearchBox.svelte
Labels: design

#1334 fix: Address bugs in SvelteKit “Preloading” tutorial example
  apps/svelte.dev/content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/+assets/app-a/src/routes/+layout.svelte
  apps/svelte.dev/content/tutorial/04-advanced-sveltekit/03-link-options/01-preload/+assets/app-b/src/routes/+layout.svelte
Labels: docs (functionality)
